-- MySQL Script generated by MySQL Workbench
-- Tue Mar  8 15:02:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema engagement-db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `engagement-db` ;

-- -----------------------------------------------------
-- Schema engagement-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `engagement-db` DEFAULT CHARACTER SET utf8 ;
USE `engagement-db` ;

-- -----------------------------------------------------
-- Table `engagement-db`.`Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `engagement-db`.`Post` ;

CREATE TABLE IF NOT EXISTS `engagement-db`.`Post` (
  `post_id` VARCHAR(40) NOT NULL,
  `post_author` VARCHAR(15) NULL,
  `post_text` VARCHAR(280) NULL,
  `date_posted` DATETIME NOT NULL,
  `date_found` DATETIME NOT NULL,
  `url` VARCHAR(280) NULL,
  PRIMARY KEY (`post_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `engagement-db`.`Attachment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `engagement-db`.`Attachment` ;

CREATE TABLE IF NOT EXISTS `engagement-db`.`Attachment` (
  `post_id` VARCHAR(40) NOT NULL,
  `attachment_id` VARCHAR(45) NOT NULL,
  `url` VARCHAR(2048) NOT NULL,
  PRIMARY KEY (`post_id`, `attachment_id`),
  CONSTRAINT `FK_Attachment_Post`
    FOREIGN KEY (`post_id`)
    REFERENCES `engagement-db`.`Post` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `engagement-db`.`University`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `engagement-db`.`University` ;

CREATE TABLE IF NOT EXISTS `engagement-db`.`University` (
  `university_name` VARCHAR(100) NOT NULL,
  `post_id` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`university_name`, `post_id`),
  INDEX `post_id_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `FK_University_Post`
    FOREIGN KEY (`post_id`)
    REFERENCES `engagement-db`.`Post` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS user1;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'user1';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
